name: Build and Deploy Next.js Application to DigitalOcean

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install
        working-directory: packages/nextjs

      - name: Build Next.js Application
        run: yarn build
        working-directory: packages/nextjs

      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "packages/nextjs/.next"
          target: "/var/www/Stormbit-monorepo/packages/nextjs/.next"

      - name: Restart PM2 Process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/Stormbit-monorepo/packages/nextjs
            pm2 restart all  # Adjust if needed
