name: Build and Deploy to Droplet

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install
        working-directory: .

      - name: Build Next.js Application
        run: yarn build
        working-directory: packages/nextjs

      - name: Restart PM2 Process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/Stormbit-monorepo
            git pull origin main
            pm2 stop stormbit
            yarn install
            cd packages/nextjs
            yarn build
            pm2 restart stormbit
